FROM python:3.8-slim

# Set working directory
WORKDIR /app

COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "watchlist_runner.py"]
