FROM nginx:alpine

# Metadata labels
LABEL org.opencontainers.image.source="https://github.com/westsurname/scripts"
LABEL org.opencontainers.image.description="Docker image for the plex_request_nginx service"

COPY plex_request_nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 8000 to the outside world
EXPOSE 8000

CMD ["nginx", "-g", "daemon off;"]
