FROM python:3.8-slim

# Set working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install gunicorn and other dependencies
RUN pip install --no-cache-dir gunicorn -r requirements.txt

# Expose port 8000 to the outside world
EXPOSE 8000

# Run gunicorn on port 8000, add more workers if required
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "plex_request_wsgi:app"]

